source 'https://github.com/Chj1995/FFSpecs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'FFAuthorKit_Example' do
  pod 'FFAuthorKit', :path => '../'

  target 'FFAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
